//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_uuidgen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("my_uuidgen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --hexgroups.
        /// </summary>
        public static string HexGroupsSwitch {
            get {
                return ResourceManager.GetString("HexGroupsSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --hyphensonly.
        /// </summary>
        public static string HyphensOnlySwitch {
            get {
                return ResourceManager.GetString("HyphensOnlySwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --no-copy.
        /// </summary>
        public static string NoCopySwitch {
            get {
                return ResourceManager.GetString("NoCopySwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --noformat.
        /// </summary>
        public static string NoFormatSwitch {
            get {
                return ResourceManager.GetString("NoFormatSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --parens.
        /// </summary>
        public static string ParensSwitch {
            get {
                return ResourceManager.GetString("ParensSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --registry.
        /// </summary>
        public static string RegistrySwitch {
            get {
                return ResourceManager.GetString("RegistrySwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --uppercase.
        /// </summary>
        public static string UppercaseSwitch {
            get {
                return ResourceManager.GetString("UppercaseSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --version.
        /// </summary>
        public static string VersionSwitch {
            get {
                return ResourceManager.GetString("VersionSwitch", resourceCulture);
            }
        }
    }
}